"""导出 API（HAR/JSON/python-requests/postman/curl/csv）。适配新 flows 表结构。"""

import csv
import io
import json
import os
import sys

from fastapi import APIRouter
from pydantic import BaseModel

from .. import db
from . import err, ok

router = APIRouter()


class ExportRequest(BaseModel):
    format: str = "json"  # json | har | python-requests | postman | curl | csv


def _parse_headers(raw: str | None) -> list:
    """解析 headers 字段为 HAR 的 [{name, value}] 列表。"""
    if not raw:
        return []
    try:
        obj = json.loads(raw)
        if isinstance(obj, dict):
            return [{"name": k, "value": str(v)} for k, v in obj.items()]
        return obj
    except Exception:  # noqa: BLE001
        return []


def _headers_dict(raw: str | None) -> dict:
    if not raw:
        return {}
    try:
        obj = json.loads(raw)
        return obj if isinstance(obj, dict) else {}
    except Exception:  # noqa: BLE001
        return {}


def _build_har(session: dict, flows: list[dict]) -> dict:
    """从流量记录构建 HAR 1.2 结构。"""
    entries = []
    for f in flows:
        entry = {
            "startedDateTime": f.get("timestamp"),
            "time": f.get("duration_ms") or 0,
            "request": {
                "method": f.get("method") or "GET",
                "url": f.get("url") or "",
                "httpVersion": "HTTP/1.1",
                "cookies": [],
                "headers": _parse_headers(f.get("request_headers")),
                "queryString": [],
                "headersSize": -1,
                "bodySize": len(f.get("request_body") or ""),
            },
            "response": {
                "status": f.get("status_code") or 0,
                "statusText": "",
                "httpVersion": "HTTP/1.1",
                "cookies": [],
                "headers": _parse_headers(f.get("response_headers")),
                "content": {
                    "size": f.get("size") or 0,
                    "mimeType": "text/plain",
                    "text": f.get("response_body") or "",
                },
                "redirectURL": "",
                "headersSize": -1,
                "bodySize": f.get("size") or -1,
            },
            "cache": {},
            "timings": {"send": 0, "wait": f.get("duration_ms") or 0, "receive": 0},
        }
        if f.get("request_body"):
            entry["request"]["postData"] = {
                "mimeType": "text/plain",
                "text": f["request_body"],
            }
        entries.append(entry)
    return {
        "log": {
            "version": "1.2",
            "creator": {"name": "Telnix", "version": "0.1.0"},
            "entries": entries,
        }
    }


def _build_python_requests(flows: list[dict]) -> str:
    """导出为 Python requests 脚本。二进制 body 用 base64.b64decode。

    Windows 上把每条 flow 的二进制 body 写到 flow_<i>_body.bin，
    脚本里改用 open('flow_<i>_body.bin','rb') 读取，避免内联大段 base64。
    """
    is_windows = sys.platform.startswith("win")
    lines = [
        "# -*- coding: utf-8 -*-",
        '"""Auto-generated by Telnix. 每条流量一个 requests 调用。"""',
        "import requests",
        "import base64",
        "import json as _json",
        "",
        "",
    ]
    for i, f in enumerate(flows, 1):
        method = (f.get("method") or "GET").lower()
        url = f.get("url") or ""
        headers = _headers_dict(f.get("request_headers"))
        # 去掉 host/content-length/connection
        for k in list(headers.keys()):
            if k.lower() in ("host", "content-length", "connection"):
                del headers[k]
        body = f.get("request_body") or ""
        lines.append(f"# ---- Flow #{f.get('id', i)} ----")
        lines.append(f"def flow_{i}():")
        lines.append(f"    url = {_py_str(url)}")
        lines.append(f"    headers = {_py_dict(headers)}")
        if body:
            if body.startswith("base64:"):
                b64 = body[7:]
                if is_windows:
                    # Windows：写 flow_<i>_body.bin，脚本用 open() 读取
                    bin_path = f"flow_{i}_body.bin"
                    try:
                        import base64 as _b64
                        raw = _b64.b64decode(b64)
                        with open(bin_path, "wb") as bf:
                            bf.write(raw)
                    except Exception:  # noqa: BLE001
                        pass
                    lines.append(f"    with open({bin_path!r}, 'rb') as _f:  # 二进制 body 从外部文件读取")
                    lines.append(f"        data = _f.read()")
                else:
                    lines.append(f"    data = base64.b64decode({_py_str(b64)})  # 二进制 body")
                lines.append(f"    resp = requests.{method}(url, headers=headers, data=data, verify=False, timeout=30)")
            else:
                # 尝试作为 JSON
                try:
                    parsed = json.loads(body)
                    lines.append(f"    json_body = {_py_repr(parsed)}")
                    lines.append(f"    resp = requests.{method}(url, headers=headers, json=json_body, verify=False, timeout=30)")
                except Exception:  # noqa: BLE001
                    lines.append(f"    data = {_py_str(body)}")
                    lines.append(f"    resp = requests.{method}(url, headers=headers, data=data, verify=False, timeout=30)")
        else:
            lines.append(f"    resp = requests.{method}(url, headers=headers, verify=False, timeout=30)")
        lines.append("    return resp")
        lines.append("")
    lines.append("if __name__ == '__main__':")
    for i in range(1, len(flows) + 1):
        lines.append(f"    flow_{i}()")
    return "\n".join(lines)


def _build_postman(flows: list[dict]) -> dict:
    """导出为 Postman Collection v2.1。二进制 body 用 raw + base64 标记。

    Windows 上把每条 flow 的二进制 body 写到 flow_<i>_body.bin，
    Postman 用 file 模式引用该文件。
    """
    is_windows = sys.platform.startswith("win")
    items = []
    for i, f in enumerate(flows, 1):
        headers = _headers_dict(f.get("request_headers"))
        header_list = [{"key": k, "value": str(v), "type": "text"}
                       for k, v in headers.items()
                       if k.lower() not in ("host", "content-length", "connection")]
        item = {
            "name": f"{f.get('method', 'GET')} {f.get('path', f.get('url', ''))}",
            "request": {
                "method": f.get("method") or "GET",
                "header": header_list,
                "url": {
                    "raw": f.get("url") or "",
                    "protocol": f.get("scheme") or "https",
                    "host": (f.get("host") or "").split("."),
                    "path": (f.get("path") or "/").split("/"),
                },
            },
        }
        body = f.get("request_body") or ""
        if body:
            if body.startswith("base64:"):
                if is_windows:
                    # Windows：写 flow_<i>_body.bin，Postman file 模式引用
                    bin_path = f"flow_{i}_body.bin"
                    try:
                        import base64 as _b64
                        raw = _b64.b64decode(body[7:])
                        with open(bin_path, "wb") as bf:
                            bf.write(raw)
                    except Exception:  # noqa: BLE001
                        pass
                    item["request"]["body"] = {
                        "mode": "file",
                        "file": {"src": bin_path},
                        "description": "binary body 从外部文件读取（Windows 兼容）",
                    }
                else:
                    item["request"]["body"] = {
                        "mode": "raw",
                        "raw": body[7:],
                        "options": {"raw": {"language": "text"}},
                        "description": "base64-encoded binary body, decode before send",
                    }
            else:
                item["request"]["body"] = {
                    "mode": "raw",
                    "raw": body,
                    "options": {"raw": {"language": "json"}},
                }
        items.append(item)
    return {
        "info": {
            "name": "Telnix Export",
            "schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json",
        },
        "item": items,
    }


def _build_curl(flows: list[dict]) -> str:
    """导出为 curl 命令脚本。二进制 body 用 base64 管道内联。"""
    lines = ["#!/bin/bash", "# Auto-generated by Telnix", ""]
    for f in flows:
        method = f.get("method") or "GET"
        url = f.get("url") or ""
        headers = _headers_dict(f.get("request_headers"))
        body = f.get("request_body") or ""
        if body and body.startswith("base64:"):
            # 二进制 body：echo + base64 -d + curl --data-binary @-
            b64 = body[7:]
            prefix = f'echo "{b64}" | base64 -d | '
            parts = ["curl", "-X", method]
            for k, v in headers.items():
                if k.lower() in ("host", "content-length", "connection"):
                    continue
                parts += ["-H", f'{k}: {v}']
            parts += ["--data-binary", "@-"]
            parts.append(url)
            lines.append(prefix + " ".join(parts))
        else:
            parts = ["curl", "-X", method]
            for k, v in headers.items():
                if k.lower() in ("host", "content-length", "connection"):
                    continue
                parts += ["-H", f'{k}: {v}']
            if body:
                parts += ["-d", body]
            parts.append(url)
            lines.append(" ".join(parts))
    return "\n".join(lines)


def _build_csv(flows: list[dict]) -> str:
    """导出为 CSV（表格分析用）。列：id,timestamp,method,host,path,status_code,duration_ms,size,process_name,pid,protocol。"""
    buf = io.StringIO()
    writer = csv.writer(buf)
    writer.writerow(["id", "timestamp", "method", "host", "path", "url",
                     "status_code", "duration_ms", "size", "process_name", "pid", "protocol"])
    for f in flows:
        writer.writerow([
            f.get("id", ""),
            f.get("timestamp", ""),
            f.get("method", ""),
            f.get("host", ""),
            f.get("path", ""),
            f.get("url", ""),
            f.get("status_code", ""),
            f.get("duration_ms", ""),
            f.get("size", ""),
            f.get("process_name", ""),
            f.get("pid", ""),
            f.get("protocol", "http"),
        ])
    return buf.getvalue()


def _py_str(s: str) -> str:
    return repr(s)


def _py_dict(d: dict) -> str:
    return repr(d)


def _py_repr(obj) -> str:
    return repr(obj)


@router.post("/export/{session_id}")
async def export_session(session_id: int, body: ExportRequest):
    """导出会话数据（HAR/JSON/python-requests/postman/curl）。"""
    session = db.get_session(session_id)
    if not session:
        return err("会话不存在")
    flows = db.get_flows(session_id, limit=100000, offset=0)
    if body.format == "json":
        return ok({"format": "json",
                   "content": {"session": session, "flows": flows}})
    if body.format == "har":
        return ok({"format": "har", "content": _build_har(session, flows)})
    if body.format == "python-requests":
        return ok({"format": "python-requests", "content": _build_python_requests(flows)})
    if body.format == "postman":
        return ok({"format": "postman", "content": _build_postman(flows)})
    if body.format == "curl":
        return ok({"format": "curl", "content": _build_curl(flows)})
    if body.format == "csv":
        return ok({"format": "csv", "content": _build_csv(flows)})
    return err("不支持的导出格式")
